# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
    # JankyBorders has a built-in detection of already running process,
    # so it won't be run twice on AeroSpace restart
    'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[exec.env-vars]
SHELL = "/etc/profiles/per-user/shreeram/bin/zsh"

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 5
inner.vertical =   5
outer.left =       5
outer.bottom =     5
outer.top =        5
outer.right =      5

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

alt-enter = 'exec-and-forget /etc/profiles/per-user/shreeram/bin/kitty -1 -d ~'
alt-m = 'exec-and-forget /etc/profiles/per-user/shreeram/bin/kitty -1 -d ~ neomutt'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = ['focus --boundaries-action stop left', 'move-mouse window-force-center']
alt-j = ['focus --boundaries-action stop down', 'move-mouse window-force-center']
alt-k = ['focus --boundaries-action stop up', 'move-mouse window-force-center']
alt-l = ['focus --boundaries-action stop right', 'move-mouse window-force-center']

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
shift-alt-h = 'move left'
shift-alt-j = 'move down'
shift-alt-k = 'move up'
shift-alt-l = 'move right'

ctrl-alt-h = 'join-with left'
ctrl-alt-j = 'join-with down'
ctrl-alt-k = 'join-with up'
ctrl-alt-l = 'join-with right'

alt-s = 'split horizontal'
alt-v = 'split vertical'

alt-f = 'fullscreen'
shift-alt-f = 'macos-native-fullscreen'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-o = 'workspace prev'
alt-i = 'workspace next'
shift-alt-o = ['move-node-to-workspace prev', 'workspace prev']
shift-alt-i = ['move-node-to-workspace next', 'workspace next']

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

shift-alt-1 = ['move-node-to-workspace 1', 'workspace 1']
shift-alt-2 = ['move-node-to-workspace 2', 'workspace 2']
shift-alt-3 = ['move-node-to-workspace 3', 'workspace 3']
shift-alt-4 = ['move-node-to-workspace 4', 'workspace 4']
shift-alt-5 = ['move-node-to-workspace 5', 'workspace 5']
shift-alt-6 = ['move-node-to-workspace 6', 'workspace 6']
shift-alt-7 = ['move-node-to-workspace 7', 'workspace 7']
shift-alt-8 = ['move-node-to-workspace 8', 'workspace 8']
shift-alt-9 = ['move-node-to-workspace 9', 'workspace 9']

alt-r = 'mode resize'
alt-semicolon = 'mode utility'

[mode.resize.binding]
s = ['balance-sizes', 'mode main']
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
alt-r = 'mode main'
esc = 'mode main'
enter = 'mode main'

[mode.utility.binding]
s = ['balance-sizes', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
c = ['reload-config', 'mode main']
alt-semicolon = 'mode main'
esc = 'mode main'
enter = 'mode main'

[key-mapping.key-notation-to-key-code]
q = 'q'
w = 'w'
f = 'e'
p = 'r'
g = 't'
j = 'y'
l = 'u'
u = 'i'
y = 'o'
semicolon = 'p'
leftSquareBracket = 'leftSquareBracket'
rightSquareBracket = 'rightSquareBracket'
backslash = 'backslash'

a = 'a'
r = 's'
s = 'd'
t = 'f'
d = 'g'
h = 'h'
n = 'j'
e = 'k'
i = 'l'
o = 'semicolon'
quote = 'quote'

z = 'z'
x = 'x'
c = 'c'
v = 'v'
b = 'b'
k = 'n'
m = 'm'
comma = 'comma'
period = 'period'
slash = 'slash'
