[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[manager.prepend_keymap]]
on = "<C-Space>"
run = '''
  shell 'qlmanage -p "$@"' --confirm
'''

[[manager.prepend_keymap]]
on = "<Tab>"
run = "tab_create --current"
desc = "Create a new tab with CWD"

[[manager.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "t"
run = ["toggle --state=none", "arrow 1"]
desc = "Toggle the current selection state"

[[manager.prepend_keymap]]
on   = "<C-t>"
run  = "toggle_all --state=true"
desc = "Select all files"


[[manager.prepend_keymap]]
on   = "<C-r>"
run  = "toggle_all --state=false"
desc = "Unselect all files"
